runtime: java17
entrypoint: 'java -jar equilibria-alchemy-1.0-all.jar'
instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 1
inbound_services:
  - warmup
includes:
  - src/main/appengine/env.yaml